language: php
env:
  global:
    - COVERAGE=false
    - XDEBUG_MODE=coverage

matrix:
  include:
    - php: 7.1
      env: CARBON_V=2
    - php: 7.2
      env: CARBON_V=2
    - php: 7.3
      env: CARBON_V=2
    - php: 7.4
      env: CARBON_V=2
    - php: 8.0
      env:
        - CARBON_V=2
        - COVERAGE=true

# Commands to be run before your environment runs.
before_script:
  - composer self-update
  - composer install --no-interaction --dev

# Commands you want to run that will verify your build.
script:
    - ./tests/carbon-${CARBON_V}.sh
    - if [[ $COVERAGE = 'true' ]]; then ./vendor/bin/phpunit --coverage-clover=build/logs/clover.xml; fi

after_success:
    - if [[ $COVERAGE = 'true' ]]; then travis_retry php vendor/bin/php-coveralls; fi

# Cache composer packages so "composer install" is faster
cache:
  directories:
    - $HOME/.composer/cache/files
